name: Continuous Deployment Workflow

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create evironment variable
        run: echo "${{ secrets.ENV_STAGING }}" >> .env
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract Git Tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/agora-api:${{ github.sha }}
      - name: Verify
        run: |
          echo GIT_TAG=$GIT_TAG
          echo GITHUB_REF=$GITHUB_REF
          echo GITHUB_REF_NAME=$GITHUB_REF_NAME
          echo GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER
          echo ${{ steps.docker_build.outputs.digest }}
