name: Generage coverage Workflow

on:
  pull_request_target:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  coverage:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: run unit tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
